// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 SFS.it di Zanutto Agostino

// Package proxy generates the NGINX reverse-proxy configuration from the
// resolved backend set and applies it atomically. See BLUEPRINT.md §16.3 and
// the auth_request contract §4. The generated file is consumed by the NGINX
// container, which validates (`nginx -t`) and hot-reloads it.
package proxy

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"xaltorka/models"
)

// GenConfig holds the parameters needed to render the vhosts.
type GenConfig struct {
	// Upstream is the internal address of the Go auth service, e.g. "xaltorka:8080".
	Upstream string
	// GateLoginURL is the public base URL of the gateway (for the login redirect).
	GateLoginURL string
	// Resolver is the DNS server NGINX uses to resolve backend upstreams at
	// request time (docker embedded DNS = 127.0.0.11). When set, proxy_pass uses
	// a variable so NGINX won't fail to (re)load if a backend is temporarily down.
	Resolver string
	// CertDir is the directory (as NGINX sees it) holding per-host certificates
	// named <host>.crt / <host>.key. When HasCert reports a cert for a host, an
	// HTTPS listener referencing those files is emitted alongside the HTTP one.
	CertDir string
	// HasCert reports whether a TLS certificate exists for a host (nil = no TLS).
	HasCert func(host string) bool
}

// Generate renders one server{} block per HOST — not per backend. Several services
// may share a hostname by mounting on different paths (e.g. the site itself on "/"
// plus a reverse-proxied service on "/bottiglia2"): they are grouped into a single
// server{} so nginx does not see a duplicate server_name (which would silently
// shadow all but the first). Backends with no host or no routes are skipped.
// Output is deterministic (hosts sorted, backends within a host by id).
func Generate(g GenConfig, backends []models.Backend) string {
	var b strings.Builder
	b.WriteString("# GENERATED by Xal-Tor-Ka proxy manager — do NOT edit by hand.\n")
	b.WriteString("# Regenerated on every service reload/start.\n\n")

	// $connection_upgrade drives the Connection header for WebSocket backends: it
	// echoes "upgrade" for a WebSocket handshake and "close" otherwise, so enabling
	// WebSocket on a vhost does not break plain keep-alive requests.
	b.WriteString("map $http_upgrade $connection_upgrade { default upgrade; \"\" close; }\n\n")

	byHost := map[string][]models.Backend{}
	var hosts []string
	for _, be := range backends {
		if be.Host == "" || len(be.Routes) == 0 {
			continue
		}
		if _, seen := byHost[be.Host]; !seen {
			hosts = append(hosts, be.Host)
		}
		byHost[be.Host] = append(byHost[be.Host], be)
	}
	sort.Strings(hosts)

	for _, h := range hosts {
		writeServer(&b, g, orderGroup(byHost[h]))
	}
	return b.String()
}

// orderGroup sorts the backends sharing a host deterministically (by id) and puts
// the PRIMARY first. The primary is the backend owning the root route "/" — the
// site itself — and it is the one whose server-level settings (TLS/www, WAF,
// client_max_body_size, custom_server) apply to the whole hostname. Services
// mounted on a sub-path contribute their location{} blocks only.
func orderGroup(grp []models.Backend) []models.Backend {
	out := append([]models.Backend{}, grp...)
	sort.SliceStable(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	for i, be := range out {
		if ownsRoot(be) {
			out[0], out[i] = out[i], out[0]
			break
		}
	}
	return out
}

// ownsRoot reports whether the backend serves the root path "/" (or an empty path,
// which writeLocation normalises to "/").
func ownsRoot(be models.Backend) bool {
	for _, rt := range be.Routes {
		if rt.Path == "/" || rt.Path == "" {
			return true
		}
	}
	return false
}

// writeServer renders the single server{} block shared by all backends mounted on
// one hostname. grp[0] is the primary (see orderGroup): its host-level settings
// drive the block; every backend in the group contributes its own location{}s,
// each with its OWN NginxOpts — so a per-service custom_location stays confined to
// that service and never leaks into the other services on the same host.
func writeServer(b *strings.Builder, g GenConfig, grp []models.Backend) {
	be := grp[0] // primary — owns the host-level settings
	fmt.Fprintf(b, "server {\n")
	b.WriteString("    listen 80;\n")
	tls := g.HasCert != nil && g.CertDir != "" && g.HasCert(be.Host)
	if tls {
		dir := strings.TrimRight(g.CertDir, "/")
		b.WriteString("    listen 443 ssl;\n")
		fmt.Fprintf(b, "    ssl_certificate %s/%s.crt;\n", dir, be.Host)
		fmt.Fprintf(b, "    ssl_certificate_key %s/%s.key;\n", dir, be.Host)
	}
	serverName := be.Host
	if be.WWW {
		serverName = be.Host + " www." + be.Host // also answer www.<host>
	}
	fmt.Fprintf(b, "    server_name %s;\n", serverName)
	if g.Resolver != "" {
		fmt.Fprintf(b, "    resolver %s valid=10s ipv6=off;\n", g.Resolver)
	}
	b.WriteString("    add_header X-Frame-Options \"SAMEORIGIN\" always;\n")
	b.WriteString("    add_header X-Content-Type-Options \"nosniff\" always;\n")
	b.WriteString("    add_header X-XSS-Protection \"0\" always;\n")
	if tls {
		b.WriteString("    add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;\n")
	}
	if be.Nginx.MaxBodyMB > 0 {
		fmt.Fprintf(b, "    client_max_body_size %dm;\n", be.Nginx.MaxBodyMB)
	}
	writeCustom(b, "    ", be.Nginx.CustomServer)
	// WAF (ModSecurity + OWASP CRS), per-vhost. The module is loaded by the nginx
	// image; here we turn it on for this server and pick the shared rules file by
	// mode: block (SecRuleEngine On) vs detect-only (log). Dormant unless enabled.
	if be.Waf != nil && be.Waf.Enabled {
		file := "xtk-detect.conf"
		if be.Waf.Mode == "block" {
			file = "xtk-block.conf"
		}
		b.WriteString("    modsecurity on;\n")
		// Per-vhost IP allow-list: these clients bypass the WAF entirely. Loaded FIRST
		// (phase 1, engine off) so it wins before CRS runs. REMOTE_ADDR is the real
		// client IP (docker DNAT preserves the source).
		if len(be.Waf.IgnoreIPs) > 0 {
			fmt.Fprintf(b, "    modsecurity_rules '\n"+
				"        SecRule REMOTE_ADDR \"@ipMatch %s\" \"id:9009001,phase:1,pass,nolog,ctl:ruleEngine=Off\"\n"+
				"    ';\n", strings.Join(be.Waf.IgnoreIPs, ","))
		}
		// Raw per-vhost ModSecurity directives (advanced escape hatch): conditional
		// disable rules etc., injected verbatim BEFORE the CRS so phase-1 conditions win.
		if s := strings.TrimSpace(be.Waf.CustomRules); s != "" {
			b.WriteString("    modsecurity_rules '\n")
			for _, line := range strings.Split(s, "\n") {
				b.WriteString("        " + strings.TrimRight(line, "\r") + "\n")
			}
			b.WriteString("    ';\n")
		}
		fmt.Fprintf(b, "    modsecurity_rules_file /etc/modsecurity.d/%s;\n", file)
		// Per-vhost disabled CRS rules (false-positive relief) — removed AFTER the CRS loads.
		if len(be.Waf.DisabledRules) > 0 {
			ids := make([]string, len(be.Waf.DisabledRules))
			for i, id := range be.Waf.DisabledRules {
				ids[i] = strconv.Itoa(id)
			}
			fmt.Fprintf(b, "    modsecurity_rules 'SecRuleRemoveById %s';\n", strings.Join(ids, " "))
		}
	}
	b.WriteString("\n")

	// ACME HTTP-01 challenge (always on :80), served as static files from the
	// shared cert dir (webroot): the issuer — the running service OR the `cert`
	// CLI — writes <certdir>/.well-known/acme-challenge/<token>, so issuance is
	// decoupled from the auth service process (no admin session needed).
	acmeRoot := strings.TrimRight(g.CertDir, "/")
	if acmeRoot == "" {
		acmeRoot = "/etc/nginx/certs"
	}
	fmt.Fprintf(b, "    location /.well-known/acme-challenge/ {\n"+
		"        default_type text/plain;\n"+
		"        root %s;\n"+
		"    }\n\n", acmeRoot)

	fmt.Fprintf(b, "    location = /__auth {\n"+
		"        internal;\n"+
		"        proxy_pass http://%s/validate;\n"+
		"        proxy_pass_request_body off;\n"+
		"        proxy_set_header Content-Length \"\";\n"+
		"        proxy_set_header X-Original-Host $host;\n"+
		"        proxy_set_header X-Original-URI $request_uri;\n"+
		"        proxy_set_header X-Real-IP $remote_addr;\n"+
		"        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"+
		"    }\n\n", g.Upstream)

	// Xal-Tor-Ka interface endpoints served on THIS host: login and 2FA happen on
	// the backend's domain → reliable host-only cookie (no cross-subdomain SSO,
	// which is unreliable on *.localhost). In production, for SSO, use a real
	// parent domain + session.cookie_domain.
	//
	// These reserved paths are served by the gate ONLY when this backend uses the gate's
	// auth UI (a non-public route). Gate static assets live under /_xtk/ (NOT /assets/),
	// so even an AUTH-GATED site keeps its own /assets/ — the login/2FA UI pulls its
	// CSS/JS from /_xtk/assets/. A fully-public backend gets NONE of these (pure
	// pass-through: it owns all its paths, /assets/ included).
	if groupUsesAuth(grp) {
		for _, p := range []string{"/login", "/auth/", "/logout", "/listing", "/_xtk/"} {
			fmt.Fprintf(b, "    location %s {\n", p)
			fmt.Fprintf(b, "        proxy_pass http://%s;\n", g.Upstream)
			b.WriteString("        proxy_set_header Host $host;\n")
			b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
			b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
			b.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
			b.WriteString("    }\n\n")
		}
	}

	// Every backend on this host contributes its routes, each rendered with its own
	// NginxOpts. Paths are de-duplicated across the group: two services declaring the
	// same host+path would otherwise emit a duplicate location{} and nginx would
	// REJECT the whole config — taking every site down. First wins (primary first).
	seen := map[string]bool{}
	idx := 0
	for _, member := range grp {
		for _, rt := range member.Routes {
			p := rt.Path
			if p == "" {
				p = "/"
			}
			if seen[p] {
				continue
			}
			seen[p] = true
			writeLocation(b, g, rt, idx, member.Nginx)
			idx++
		}
	}

	// Redirect to login on the SAME host (host-only cookie), then return to the
	// requested page.
	b.WriteString("    location @login { return 302 /login?next=$request_uri; }\n")
	b.WriteString("    location @forbidden { return 403; }\n")
	b.WriteString("}\n\n")
}

// backendUsesAuth reports whether any of the backend's routes require the gate's auth
// (rule != "public"). Only then does the host need the gate's reserved paths (/login,
// /assets/, …); a fully-public backend is pure pass-through.
func backendUsesAuth(be models.Backend) bool {
	for _, rt := range be.Routes {
		if rt.Rule != "public" {
			return true
		}
	}
	return false
}

// groupUsesAuth reports whether ANY service sharing this hostname needs the gate's
// auth UI. The reserved paths (/login, /_xtk/, …) are emitted once per server{}, so
// a public site gains them as soon as one gated service is mounted on a sub-path —
// that is required, otherwise the login redirect for that service would 404.
func groupUsesAuth(grp []models.Backend) bool {
	for _, be := range grp {
		if backendUsesAuth(be) {
			return true
		}
	}
	return false
}

func writeLocation(b *strings.Builder, g GenConfig, rt models.Route, idx int, n models.NginxOpts) {
	path := rt.Path
	if path == "" {
		path = "/"
	}
	fmt.Fprintf(b, "    location %s {\n", path)
	if rt.Rule != "public" {
		b.WriteString("        auth_request /__auth;\n")
		b.WriteString("        error_page 401 = @login;\n")
		b.WriteString("        error_page 403 = @forbidden;\n")
		b.WriteString("        auth_request_set $auth_user $upstream_http_x_auth_user;\n")
		b.WriteString("        proxy_set_header X-Auth-User $auth_user;\n")
	}
	// With a resolver, proxy_pass via a variable defers DNS to request time, so a
	// down/unresolvable backend doesn't break nginx reload. $request_uri preserves
	// the original path+query (variable proxy_pass doesn't append it automatically).
	if g.Resolver != "" {
		fmt.Fprintf(b, "        set $up%d %s;\n", idx, rt.Upstream)
		fmt.Fprintf(b, "        proxy_pass $up%d$request_uri;\n", idx)
	} else {
		fmt.Fprintf(b, "        proxy_pass %s;\n", rt.Upstream)
	}
	b.WriteString("        proxy_set_header Host $host;\n")
	b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	b.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	b.WriteString("        proxy_set_header X-Forwarded-Host $host;\n")
	if n.WebSocket {
		b.WriteString("        proxy_http_version 1.1;\n")
		b.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
		b.WriteString("        proxy_set_header Connection $connection_upgrade;\n")
	}
	if n.BackendSelfSigned {
		b.WriteString("        proxy_ssl_verify off;\n")
		b.WriteString("        proxy_ssl_server_name on;\n")
	}
	if n.NoBuffering {
		b.WriteString("        proxy_buffering off;\n")
	}
	if n.ProxyTimeout > 0 {
		fmt.Fprintf(b, "        proxy_read_timeout %ds;\n", n.ProxyTimeout)
		fmt.Fprintf(b, "        proxy_send_timeout %ds;\n", n.ProxyTimeout)
	}
	writeCustom(b, "        ", n.CustomLocation)
	b.WriteString("    }\n\n")
}

// writeCustom injects raw operator-provided NGINX directives, one per line, at the
// given indent. Empty input is a no-op. Content is trusted (admin-only) and
// validated by `nginx -t` on reload (bad config keeps the previous one).
func writeCustom(b *strings.Builder, indent, raw string) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return
	}
	for _, line := range strings.Split(raw, "\n") {
		if line = strings.TrimSpace(line); line != "" {
			b.WriteString(indent + line + "\n")
		}
	}
}
