// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 SFS.it di Zanutto Agostino

// Package proxy generates the NGINX reverse-proxy configuration from the
// resolved backend set and applies it atomically. See BLUEPRINT.md §16.3 and
// the auth_request contract §4. The generated file is consumed by the NGINX
// container, which validates (`nginx -t`) and hot-reloads it.
package proxy

import (
	"fmt"
	"sort"
	"strings"

	"xaltorka/models"
)

// GenConfig holds the parameters needed to render the vhosts.
type GenConfig struct {
	// Upstream is the internal address of the Go auth service, e.g. "xaltorka:8080".
	Upstream string
	// GateLoginURL is the public base URL of the gateway (for the login redirect).
	GateLoginURL string
	// Resolver is the DNS server NGINX uses to resolve backend upstreams at
	// request time (docker embedded DNS = 127.0.0.11). When set, proxy_pass uses
	// a variable so NGINX won't fail to (re)load if a backend is temporarily down.
	Resolver string
	// CertDir is the directory (as NGINX sees it) holding per-host certificates
	// named <host>.crt / <host>.key. When HasCert reports a cert for a host, an
	// HTTPS listener referencing those files is emitted alongside the HTTP one.
	CertDir string
	// HasCert reports whether a TLS certificate exists for a host (nil = no TLS).
	HasCert func(host string) bool
}

// Generate renders one server{} block per backend host. Backends with no host
// or no routes are skipped. Output is deterministic (hosts sorted).
func Generate(g GenConfig, backends []models.Backend) string {
	var b strings.Builder
	b.WriteString("# GENERATED by Xal-Tor-Ka proxy manager — do NOT edit by hand.\n")
	b.WriteString("# Regenerated on every service reload/start.\n\n")

	sorted := append([]models.Backend{}, backends...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Host < sorted[j].Host })

	for _, be := range sorted {
		if be.Host == "" || len(be.Routes) == 0 {
			continue
		}
		writeServer(&b, g, be)
	}
	return b.String()
}

func writeServer(b *strings.Builder, g GenConfig, be models.Backend) {
	fmt.Fprintf(b, "server {\n")
	b.WriteString("    listen 80;\n")
	tls := g.HasCert != nil && g.CertDir != "" && g.HasCert(be.Host)
	if tls {
		dir := strings.TrimRight(g.CertDir, "/")
		b.WriteString("    listen 443 ssl;\n")
		fmt.Fprintf(b, "    ssl_certificate %s/%s.crt;\n", dir, be.Host)
		fmt.Fprintf(b, "    ssl_certificate_key %s/%s.key;\n", dir, be.Host)
	}
	fmt.Fprintf(b, "    server_name %s;\n", be.Host)
	if g.Resolver != "" {
		fmt.Fprintf(b, "    resolver %s valid=10s ipv6=off;\n", g.Resolver)
	}
	b.WriteString("    add_header X-Frame-Options \"SAMEORIGIN\" always;\n")
	b.WriteString("    add_header X-Content-Type-Options \"nosniff\" always;\n")
	b.WriteString("    add_header X-XSS-Protection \"0\" always;\n")
	if tls {
		b.WriteString("    add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;\n")
	}
	b.WriteString("\n")

	// ACME HTTP-01 challenge (always on :80), proxied to the auth service which
	// serves the key authorizations during certificate issuance/renewal.
	fmt.Fprintf(b, "    location /.well-known/acme-challenge/ {\n"+
		"        proxy_pass http://%s;\n"+
		"    }\n\n", g.Upstream)

	fmt.Fprintf(b, "    location = /__auth {\n"+
		"        internal;\n"+
		"        proxy_pass http://%s/validate;\n"+
		"        proxy_pass_request_body off;\n"+
		"        proxy_set_header Content-Length \"\";\n"+
		"        proxy_set_header X-Original-Host $host;\n"+
		"        proxy_set_header X-Original-URI $request_uri;\n"+
		"        proxy_set_header X-Real-IP $remote_addr;\n"+
		"        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"+
		"    }\n\n", g.Upstream)

	// Xal-Tor-Ka interface endpoints served on THIS host: login and 2FA happen on
	// the backend's domain → reliable host-only cookie (no cross-subdomain SSO,
	// which is unreliable on *.localhost). In production, for SSO, use a real
	// parent domain + session.cookie_domain.
	for _, p := range []string{"/login", "/auth/", "/logout", "/listing", "/assets/"} {
		fmt.Fprintf(b, "    location %s {\n", p)
		fmt.Fprintf(b, "        proxy_pass http://%s;\n", g.Upstream)
		b.WriteString("        proxy_set_header Host $host;\n")
		b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
		b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
		b.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
		b.WriteString("    }\n\n")
	}

	for i, rt := range be.Routes {
		writeLocation(b, g, rt, i)
	}

	// Redirect to login on the SAME host (host-only cookie), then return to the
	// requested page.
	b.WriteString("    location @login { return 302 /login?next=$request_uri; }\n")
	b.WriteString("    location @forbidden { return 403; }\n")
	b.WriteString("}\n\n")
}

func writeLocation(b *strings.Builder, g GenConfig, rt models.Route, idx int) {
	path := rt.Path
	if path == "" {
		path = "/"
	}
	fmt.Fprintf(b, "    location %s {\n", path)
	if rt.Rule != "public" {
		b.WriteString("        auth_request /__auth;\n")
		b.WriteString("        error_page 401 = @login;\n")
		b.WriteString("        error_page 403 = @forbidden;\n")
		b.WriteString("        auth_request_set $auth_user $upstream_http_x_auth_user;\n")
		b.WriteString("        proxy_set_header X-Auth-User $auth_user;\n")
	}
	// With a resolver, proxy_pass via a variable defers DNS to request time, so a
	// down/unresolvable backend doesn't break nginx reload. $request_uri preserves
	// the original path+query (variable proxy_pass doesn't append it automatically).
	if g.Resolver != "" {
		fmt.Fprintf(b, "        set $up%d %s;\n", idx, rt.Upstream)
		fmt.Fprintf(b, "        proxy_pass $up%d$request_uri;\n", idx)
	} else {
		fmt.Fprintf(b, "        proxy_pass %s;\n", rt.Upstream)
	}
	b.WriteString("        proxy_set_header Host $host;\n")
	b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	b.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	b.WriteString("    }\n\n")
}
