// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 SFS.it di Zanutto Agostino

// Package proxy generates the NGINX reverse-proxy configuration from the
// resolved backend set and applies it atomically. See BLUEPRINT.md §16.3 and
// the auth_request contract §4. The generated file is consumed by the NGINX
// container, which validates (`nginx -t`) and hot-reloads it.
package proxy

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"xaltorka/models"
)

// GenConfig holds the parameters needed to render the vhosts.
type GenConfig struct {
	// Upstream is the internal address of the Go auth service, e.g. "xaltorka:8080".
	Upstream string
	// GateLoginURL is the public base URL of the gateway (for the login redirect).
	GateLoginURL string
	// Resolver is the DNS server NGINX uses to resolve backend upstreams at
	// request time (docker embedded DNS = 127.0.0.11). When set, proxy_pass uses
	// a variable so NGINX won't fail to (re)load if a backend is temporarily down.
	Resolver string
	// CertDir is the directory (as NGINX sees it) holding per-host certificates
	// named <host>.crt / <host>.key. When HasCert reports a cert for a host, an
	// HTTPS listener referencing those files is emitted alongside the HTTP one.
	CertDir string
	// HasCert reports whether a TLS certificate exists for a host (nil = no TLS).
	HasCert func(host string) bool
}

// Generate renders one server{} block per backend host. Backends with no host
// or no routes are skipped. Output is deterministic (hosts sorted).
func Generate(g GenConfig, backends []models.Backend) string {
	var b strings.Builder
	b.WriteString("# GENERATED by Xal-Tor-Ka proxy manager — do NOT edit by hand.\n")
	b.WriteString("# Regenerated on every service reload/start.\n\n")

	// $connection_upgrade drives the Connection header for WebSocket backends: it
	// echoes "upgrade" for a WebSocket handshake and "close" otherwise, so enabling
	// WebSocket on a vhost does not break plain keep-alive requests.
	b.WriteString("map $http_upgrade $connection_upgrade { default upgrade; \"\" close; }\n\n")

	sorted := append([]models.Backend{}, backends...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Host < sorted[j].Host })

	for _, be := range sorted {
		if be.Host == "" || len(be.Routes) == 0 {
			continue
		}
		writeServer(&b, g, be)
	}
	return b.String()
}

func writeServer(b *strings.Builder, g GenConfig, be models.Backend) {
	fmt.Fprintf(b, "server {\n")
	b.WriteString("    listen 80;\n")
	tls := g.HasCert != nil && g.CertDir != "" && g.HasCert(be.Host)
	if tls {
		dir := strings.TrimRight(g.CertDir, "/")
		b.WriteString("    listen 443 ssl;\n")
		fmt.Fprintf(b, "    ssl_certificate %s/%s.crt;\n", dir, be.Host)
		fmt.Fprintf(b, "    ssl_certificate_key %s/%s.key;\n", dir, be.Host)
	}
	serverName := be.Host
	if be.WWW {
		serverName = be.Host + " www." + be.Host // also answer www.<host>
	}
	fmt.Fprintf(b, "    server_name %s;\n", serverName)
	if g.Resolver != "" {
		fmt.Fprintf(b, "    resolver %s valid=10s ipv6=off;\n", g.Resolver)
	}
	b.WriteString("    add_header X-Frame-Options \"SAMEORIGIN\" always;\n")
	b.WriteString("    add_header X-Content-Type-Options \"nosniff\" always;\n")
	b.WriteString("    add_header X-XSS-Protection \"0\" always;\n")
	if tls {
		b.WriteString("    add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;\n")
	}
	if be.Nginx.MaxBodyMB > 0 {
		fmt.Fprintf(b, "    client_max_body_size %dm;\n", be.Nginx.MaxBodyMB)
	}
	writeCustom(b, "    ", be.Nginx.CustomServer)
	// WAF (ModSecurity + OWASP CRS), per-vhost. The module is loaded by the nginx
	// image; here we turn it on for this server and pick the shared rules file by
	// mode: block (SecRuleEngine On) vs detect-only (log). Dormant unless enabled.
	if be.Waf != nil && be.Waf.Enabled {
		file := "xtk-detect.conf"
		if be.Waf.Mode == "block" {
			file = "xtk-block.conf"
		}
		b.WriteString("    modsecurity on;\n")
		// Per-vhost IP allow-list: these clients bypass the WAF entirely. Loaded FIRST
		// (phase 1, engine off) so it wins before CRS runs. REMOTE_ADDR is the real
		// client IP (docker DNAT preserves the source).
		if len(be.Waf.IgnoreIPs) > 0 {
			fmt.Fprintf(b, "    modsecurity_rules '\n"+
				"        SecRule REMOTE_ADDR \"@ipMatch %s\" \"id:9009001,phase:1,pass,nolog,ctl:ruleEngine=Off\"\n"+
				"    ';\n", strings.Join(be.Waf.IgnoreIPs, ","))
		}
		// Raw per-vhost ModSecurity directives (advanced escape hatch): conditional
		// disable rules etc., injected verbatim BEFORE the CRS so phase-1 conditions win.
		if s := strings.TrimSpace(be.Waf.CustomRules); s != "" {
			b.WriteString("    modsecurity_rules '\n")
			for _, line := range strings.Split(s, "\n") {
				b.WriteString("        " + strings.TrimRight(line, "\r") + "\n")
			}
			b.WriteString("    ';\n")
		}
		fmt.Fprintf(b, "    modsecurity_rules_file /etc/modsecurity.d/%s;\n", file)
		// Per-vhost disabled CRS rules (false-positive relief) — removed AFTER the CRS loads.
		if len(be.Waf.DisabledRules) > 0 {
			ids := make([]string, len(be.Waf.DisabledRules))
			for i, id := range be.Waf.DisabledRules {
				ids[i] = strconv.Itoa(id)
			}
			fmt.Fprintf(b, "    modsecurity_rules 'SecRuleRemoveById %s';\n", strings.Join(ids, " "))
		}
	}
	b.WriteString("\n")

	// ACME HTTP-01 challenge (always on :80), served as static files from the
	// shared cert dir (webroot): the issuer — the running service OR the `cert`
	// CLI — writes <certdir>/.well-known/acme-challenge/<token>, so issuance is
	// decoupled from the auth service process (no admin session needed).
	acmeRoot := strings.TrimRight(g.CertDir, "/")
	if acmeRoot == "" {
		acmeRoot = "/etc/nginx/certs"
	}
	fmt.Fprintf(b, "    location /.well-known/acme-challenge/ {\n"+
		"        default_type text/plain;\n"+
		"        root %s;\n"+
		"    }\n\n", acmeRoot)

	fmt.Fprintf(b, "    location = /__auth {\n"+
		"        internal;\n"+
		"        proxy_pass http://%s/validate;\n"+
		"        proxy_pass_request_body off;\n"+
		"        proxy_set_header Content-Length \"\";\n"+
		"        proxy_set_header X-Original-Host $host;\n"+
		"        proxy_set_header X-Original-URI $request_uri;\n"+
		"        proxy_set_header X-Real-IP $remote_addr;\n"+
		"        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"+
		"    }\n\n", g.Upstream)

	// Xal-Tor-Ka interface endpoints served on THIS host: login and 2FA happen on
	// the backend's domain → reliable host-only cookie (no cross-subdomain SSO,
	// which is unreliable on *.localhost). In production, for SSO, use a real
	// parent domain + session.cookie_domain.
	//
	// These reserved paths are served by the gate ONLY when this backend actually uses
	// the gate's auth UI (it has a non-public route). A FULLY-PUBLIC backend is pure
	// pass-through: it owns ALL its paths — including /assets/ — so a site whose asset
	// dir collides with the gate's (e.g. a Vite/PWA build) works without a manual
	// stopgap. (Without this, a public site's /assets/ was routed to the gate → 404.)
	if backendUsesAuth(be) {
		for _, p := range []string{"/login", "/auth/", "/logout", "/listing", "/assets/"} {
			fmt.Fprintf(b, "    location %s {\n", p)
			fmt.Fprintf(b, "        proxy_pass http://%s;\n", g.Upstream)
			b.WriteString("        proxy_set_header Host $host;\n")
			b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
			b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
			b.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
			b.WriteString("    }\n\n")
		}
	}

	for i, rt := range be.Routes {
		writeLocation(b, g, rt, i, be.Nginx)
	}

	// Redirect to login on the SAME host (host-only cookie), then return to the
	// requested page.
	b.WriteString("    location @login { return 302 /login?next=$request_uri; }\n")
	b.WriteString("    location @forbidden { return 403; }\n")
	b.WriteString("}\n\n")
}

// backendUsesAuth reports whether any of the backend's routes require the gate's auth
// (rule != "public"). Only then does the host need the gate's reserved paths (/login,
// /assets/, …); a fully-public backend is pure pass-through.
func backendUsesAuth(be models.Backend) bool {
	for _, rt := range be.Routes {
		if rt.Rule != "public" {
			return true
		}
	}
	return false
}

func writeLocation(b *strings.Builder, g GenConfig, rt models.Route, idx int, n models.NginxOpts) {
	path := rt.Path
	if path == "" {
		path = "/"
	}
	fmt.Fprintf(b, "    location %s {\n", path)
	if rt.Rule != "public" {
		b.WriteString("        auth_request /__auth;\n")
		b.WriteString("        error_page 401 = @login;\n")
		b.WriteString("        error_page 403 = @forbidden;\n")
		b.WriteString("        auth_request_set $auth_user $upstream_http_x_auth_user;\n")
		b.WriteString("        proxy_set_header X-Auth-User $auth_user;\n")
	}
	// With a resolver, proxy_pass via a variable defers DNS to request time, so a
	// down/unresolvable backend doesn't break nginx reload. $request_uri preserves
	// the original path+query (variable proxy_pass doesn't append it automatically).
	if g.Resolver != "" {
		fmt.Fprintf(b, "        set $up%d %s;\n", idx, rt.Upstream)
		fmt.Fprintf(b, "        proxy_pass $up%d$request_uri;\n", idx)
	} else {
		fmt.Fprintf(b, "        proxy_pass %s;\n", rt.Upstream)
	}
	b.WriteString("        proxy_set_header Host $host;\n")
	b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	b.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	b.WriteString("        proxy_set_header X-Forwarded-Host $host;\n")
	if n.WebSocket {
		b.WriteString("        proxy_http_version 1.1;\n")
		b.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
		b.WriteString("        proxy_set_header Connection $connection_upgrade;\n")
	}
	if n.BackendSelfSigned {
		b.WriteString("        proxy_ssl_verify off;\n")
		b.WriteString("        proxy_ssl_server_name on;\n")
	}
	if n.NoBuffering {
		b.WriteString("        proxy_buffering off;\n")
	}
	if n.ProxyTimeout > 0 {
		fmt.Fprintf(b, "        proxy_read_timeout %ds;\n", n.ProxyTimeout)
		fmt.Fprintf(b, "        proxy_send_timeout %ds;\n", n.ProxyTimeout)
	}
	writeCustom(b, "        ", n.CustomLocation)
	b.WriteString("    }\n\n")
}

// writeCustom injects raw operator-provided NGINX directives, one per line, at the
// given indent. Empty input is a no-op. Content is trusted (admin-only) and
// validated by `nginx -t` on reload (bad config keeps the previous one).
func writeCustom(b *strings.Builder, indent, raw string) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return
	}
	for _, line := range strings.Split(raw, "\n") {
		if line = strings.TrimSpace(line); line != "" {
			b.WriteString(indent + line + "\n")
		}
	}
}
